### ISSUE TITLE
[BUG][WEB] silent login

### ISSUE THREAD

**Issue by SzunTibor** [SwissCheese5/Kirama-Issues#11]
**Describe the bug**
If you reload page once logged in, it shows login screen again but once you move the mouse cursor (not 100%)  it reloads the login page again then automatically logs in.

**Desktop (please complete the following information):**
Win10 Chrome

**Comment by SaadArdati** [comment]
I'm extremely close to cracking this one.

**Comment by SaadArdati** [comment]
Should be fixed?
