### ISSUE TITLE
Janky screen swiping on intro screens on desktop app

### ISSUE THREAD

**Issue by murapix** [SwissCheese5/Kirama-Issues#2]
For the introductory screens telling you about tokens and how to get them, the swiping option just feels way off. There's initially no sign that the screen should be swiped from right to left, and when it is swiped, the swipe requires much more movement than is comfortable. Yes, there is a button to go to the next page, but when your focus is on the center of the screen, it's really hard to see that button in the far corner.

Using your scroll wheel should also be an option for progressing through the pages.

**Comment by SaadArdati** [comment]
Magically fixed?
