### ISSUE TITLE
Up-one-level button placement

### ISSUE THREAD

**Issue by murapix** [SwissCheese5/Kirama-Issues#6]
The bottom right corner isn't the first place I'd look for the functionality of going up one level in the comment chain I'm viewing. I believe it would be preferable to have a button on each comment that would take you to its parent. This may be instead of or in addition to the current solution, which probably should be moved up to the top right with the other navigation buttons if it does stay.

**Comment by SaadArdati** [comment]
Proposed a change, might change it again later.
