### ISSUE TITLE
[BUG][WEB] custom decoration settings reset if you try to edit them again

### ISSUE THREAD

**Issue by SzunTibor** [SwissCheese5/Kirama-Issues#9]
**Describe the bug**
Maybe the shape stays but spawning, colors gets messed up

**To Reproduce**
reply - custom decoration - back to edit text - custom decoration

**Screenshots**
https://i.imgur.com/tzuGSfn.png

**Desktop (please complete the following information):**
Win10 Chrome

**Comment by SaadArdati** [comment]
Fixed.
